//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Sales = new HashSet<Sales>();
            this.Appointment = new HashSet<Appointment>();
        }
    
        public int Id { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Fullname { get
            {
                return Lastname + " " + Name + " " + Surname;
            } }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
    
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual ICollection<Appointment> Appointment { get; set; }
    }
}
