//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public Sales()
        {
            this.SaleServices = new HashSet<SaleServices>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int Quantity { get; set; }
        public decimal TotalAmount { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
        public virtual ICollection<SaleServices> SaleServices { get; set; }
    }
}
