//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleServices
    {
        public int Id { get; set; }
        public int SaleId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Sales Sales { get; set; }
        public virtual Services Services { get; set; }
    }
}
